version: "3.4"
services:
  backend:
    build:
      context: .
    image: backend
    ports:
      - "8080:8080"
    environment:
      ALLOWED_ORIGIN: "http://localhost:3000"
      REDIS_ADDR: "redis:6379"
    depends_on: 
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  frontend:
    build:
      context: frontend/.
      args:
        REACT_APP_BACKEND_WS: "ws://localhost:8080"
        REACT_APP_BACKEND_URL: "http://localhost:8080"
    image: frontend
    ports:
      - "3000:80"
